spring:
  application:
    name:
      scholar-config-server
  profiles:
    active: composite

  cloud:
    config:
      server:
        composite:
          -
            type: native
            search-locations: classpath:/config
          -
            type: vault
            host: 95.163.235.242
            scheme: http
            port: 8200
            backend: secret
            kvVersion: 2

server:
  port:
    8071